=== axtux/laser-challenge/core/assets/XML_format/blocks.dtd
<!ELEMENT blocks (block*) >
<!ELEMENT block (image,name,(inputs || required-inputs))>
<!ELEMENT image (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT inputs (input*) >
<!ELEMENT required-inputs (input*) >
<!ELEMENT input (output*) >
<!ATTLIST input orientation CDATA #IMPLIED >
<!ELEMENT output EMPTY >
<!ATTLIST output orientation CDATA #IMPLIED >

=== axtux/laser-challenge/level_types/advanced/blocks.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE blocks SYSTEM "../../core/assets/XML_format/blocks.dtd">
<blocks>
	<block>
		<name>blocker</name>
		<label>Bloqueur</label>
		<inputs>
		</inputs>
	</block>
	
	<block>
		<name>gate</name>
		<label>Porte</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="DOWN"/>
			</input>
			<input orientation="DOWN">
				<output orientation="UP"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>one-laser_source</name>
		<label>Source</label>
		<inputs>
			<input>
				<output orientation ="UP"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>one-laser_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="UP"/>
		</required-inputs>
	</block>
		
	<block>
		<name>two-laser_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="RIGHT"/>
			<input orientation ="LEFT"/>
		</required-inputs>
	</block>
			
	<block>
		<name>four-laser_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="UP"/>
			<input orientation ="RIGHT"/>
			<input orientation ="DOWN"/>
			<input orientation ="LEFT"/>
		</required-inputs>
	</block>
	
	<block>
		<name>one-laser-oriented_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="DOWN_RIGHT"/>
		</required-inputs>
	</block>
	
	<block>
		<name>two-laser-oriented_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="DOWN_RIGHT"/>
			<input orientation ="DOWN_LEFT"/>
		</required-inputs>
	</block>
	
	<block>
		<name>two-laser-middle-oriented_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="UP"/>
			<input orientation ="DOWN_RIGHT"/>
		</required-inputs>
	</block>
	
	<block>
		<name>four-laser-oriented_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="UP_LEFT"/>
			<input orientation ="UP_RIGHT"/>
			<input orientation ="DOWN_LEFT"/>
			<input orientation ="DOWN_RIGHT"/>
		</required-inputs>
	</block>
			
	<block>
		<name>one-way_mirror</name>
		<label>Miroir</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT"/>
			</input>
			<input orientation="RIGHT">
				<output orientation="UP"/>
			</input>
		</inputs>
	</block>

	<block>
		<name>one-way-oriented_mirror</name>
		<label>Miroir</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="UP_RIGHT"/>
			</input>
			<input orientation="UP_RIGHT">
				<output orientation="UP"/>
			</input>
		</inputs>
	</block>


	<block>
		<name>two-way_mirror</name>
		<label>Miroir</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT"/>
			</input>
			<input orientation="RIGHT">
				<output orientation="UP"/>
			</input>
			<input orientation="DOWN">
				<output orientation="LEFT"/>
			</input>
			<input orientation="LEFT">
				<output orientation="DOWN"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-straight_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="LEFT" intensite="1/2"/>
				<output orientation ="RIGHT" intensite="1/2"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-angled-right_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="DOWN" intensite="1/2"/>
				<output orientation ="RIGHT" intensite="1/2"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-angled-left_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="LEFT" intensite="1/2"/>
				<output orientation ="DOWN" intensite="1/2"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-little-angled_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="UP_LEFT" intensite="1/2"/>
				<output orientation ="UP_RIGHT" intensite="1/2"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-big-angled_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="DOWN_LEFT" intensite="1/2"/>
				<output orientation ="DOWN_RIGHT" intensite="1/2"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>three-way_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT" intensite="1/3"/>
				<output orientation ="LEFT" intensite="1/3"/>
				<output orientation ="DOWN" intensite="1/3"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>three-way-little-angled_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="UP_RIGHT" intensite="1/3"/>
				<output orientation ="UP_LEFT" intensite="1/3"/>
				<output orientation ="DOWN" intensite="1/3"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>four-way-left_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="UP_LEFT" intensite="1/4"/>
				<output orientation ="RIGHT" intensite="1/4"/>
				<output orientation ="DOWN" intensite="1/4"/>
				<output orientation ="LEFT" intensite="1/4"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>five-way_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT" intensite="1/5"/>
				<output orientation ="DOWN_RIGHT" intensite="1/5"/>
				<output orientation ="DOWN" intensite="1/5"/>
				<output orientation ="DOWN_LEFT" intensite="1/5"/>
				<output orientation ="LEFT" intensite="1/5"/>
			</input>
		</inputs>
	</block>
	
	
	<block>
		<name>amplifier</name>
		<label>Amplificateur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="DOWN" intensite="2"/>
			</input>
		</inputs>
	</block>
	
</blocks>

=== axtux/laser-challenge/implementation/level_types/standard/blocks.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE blocks SYSTEM "../../core/assets/XML_format/blocks.dtd">


<blocks>
	<block>
		<name>blocker</name>
		<label>Bloqueur</label>
	</block>
	
	<block>
		<name>gate</name>
		<label>Porte</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="DOWN"/>
			</input>
			<input orientation="DOWN">
				<output orientation="UP"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>one-laser_source</name>
		<label>Source</label>
		<inputs>
			<input>
				<output orientation ="UP"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>one-laser_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="UP"/>
		</required-inputs>
	</block>
	
	<block>
		<name>two-laser_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="RIGHT"/>
			<input orientation ="LEFT"/>
		</required-inputs>
	</block>
	
	<block>
		<name>four-laser_target</name>
		<label>Cible</label>
		<required-inputs>
			<input orientation ="UP"/>
			<input orientation ="RIGHT"/>
			<input orientation ="DOWN"/>
			<input orientation ="LEFT"/>
		</required-inputs>
	</block>
	
	<block>
		<name>one-way_mirror</name>
		<label>Miroir</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT"/>
			</input>
			<input orientation="RIGHT">
				<output orientation="UP"/>
			</input>
		</inputs>
	</block>

	
	<block>
		<name>two-way_mirror</name>
		<label>Miroir</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT"/>
			</input>
			<input orientation="RIGHT">
				<output orientation="UP"/>
			</input>
			<input orientation="DOWN">
				<output orientation="LEFT"/>
			</input>
			<input orientation="LEFT">
				<output orientation="DOWN"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-straight_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="LEFT"/>
				<output orientation ="RIGHT"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-angled-right_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="DOWN"/>
				<output orientation ="RIGHT"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>two-way-angled-left_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="LEFT"/>
				<output orientation ="DOWN"/>
			</input>
		</inputs>
	</block>
	
	<block>
		<name>three-way_splitter</name>
		<label>Diviseur</label>
		<inputs>
			<input orientation="UP">
				<output orientation ="RIGHT"/>
				<output orientation ="LEFT"/>
				<output orientation ="DOWN"/>
			</input>
		</inputs>
	</block>
	
</blocks>
