<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE orientations [
	<!ELEMENT orientations (orientation+) >
	<!ELEMENT orientation (#PCDATA)>
	]>
<orientations>
	<orientation>UP</orientation>
	<orientation>RIGHT</orientation>
	<orientation>DOWN</orientation>
	<orientation>LEFT</orientation>
</orientations>
	
